### ISSUE TITLE
conda-env create doesn't work if there is no prefix argument

### ISSUE THREAD

**Issue by ahmadia** [conda/conda-env#167]
This looks like a regression in the interaction with conda:

```
zsh 5652 [1] % conda list "conda*"
# packages in environment at /Users/aahmadia/anaconda:
#
anaconda                  2.3.0                np19py27_0
anaconda-client           1.0.2                    py34_0
anaconda-launcher         0.11.1                        0
conda                     3.17.0                   py34_0
conda-build               1.16.0                   py34_0
conda-env                 2.4.2                    py34_0
```

```
zsh 5655 [1] % conda env create
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/aahmadia/anaconda/bin/conda-env", line 6, in <module>
    sys.exit(main())
  File "/Users/aahmadia/anaconda/lib/python3.4/site-packages/conda_env/cli/main.py", line 68, in main
    return args_func(args, parser)
  File "/Users/aahmadia/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "/Users/aahmadia/anaconda/lib/python3.4/site-packages/conda_env/cli/main_create.py", line 87, in execute
    prefix = common.get_prefix(args, search=False)
  File "/Users/aahmadia/anaconda/lib/python3.4/site-packages/conda/cli/common.py", line 373, in get_prefix
    if args.prefix:
AttributeError: 'Namespace' object has no attribute 'prefix'
```

**Comment by ahmadia** [comment]
closely related to https://github.com/conda/conda-env/issues/168

**Comment by malev** [comment]
@ahmadia would you mind pasting here the content of the `environment.yml` file?

**Comment by ahmadia** [comment]
See https://github.com/conda/conda-env/issues/168#issuecomment-142093973

**Comment by malev** [comment]
@ahmadia I don't think they are related.
