### ISSUE TITLE
Conda env is incompatible with the current conda release

### ISSUE THREAD

**Issue by ahmadia** [conda/conda-env#168]
I think there are interactions with the `prefix` argument for package installation that are causing major failures in `conda-env`.  I think we need to get these fixed and push out a bug fix release.

**Comment by ahmadia** [comment]
I don't have time to look deeper into this, but I'm seeing errors like this:

```
zsh 5658 [1] % conda env create -n arokem2
Fetching package metadata: ....
Solving package specifications: Linking packages ...
[      COMPLETE      ]|##########################################################################################################| 100%
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/aahmadia/anaconda/bin/conda-env", line 6, in <module>
    sys.exit(main())
  File "/Users/aahmadia/anaconda/lib/python3.4/site-packages/conda_env/cli/main.py", line 68, in main
    return args_func(args, parser)
  File "/Users/aahmadia/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "/Users/aahmadia/anaconda/lib/python3.4/site-packages/conda_env/cli/main_create.py", line 99, in execute
    installer.install(prefix, pkg_specs, args, env)
  File "/Users/aahmadia/anaconda/lib/python3.4/site-packages/conda_env/installers/pip.py", line 8, in install
    pip_cmd = main_list.pip_args(prefix) + ['install', ] + specs
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
```

It looks like `prefix` isn't being populated by the conda env installer before it attempts to use it.

**Comment by ahmadia** [comment]
This happens with an `environment.yml` that doesn't contain a `name` parameter.  Revising the issue name.

**Comment by ahmadia** [comment]
The solution is to add a `name` key to your environment.yml.

**Comment by malev** [comment]
@ahmadia can you post here your `environment.yml` file? I've tried with the latest versions and worked fine for me

**Comment by ahmadia** [comment]
@malev 

```
dependencies:
- vtk=5.10.1=py27_0
- pip=7.1.2=py27_0
- pip:
  - dipy==0.9.2
  - nibabel==2.0.0
  - scikit-learn==0.16.1
```

**Comment by malev** [comment]
the problem is not related to the name of the environment.
For some reason, when you install pip like this it does not installs python with it so https://github.com/conda/conda/blob/master/conda/pip.py#L22 evaluates to False.
Not sure how to fix this issue

**Comment by gabrielelanaro** [comment]
Is there any workaround for this issue?

**Comment by ahmadia** [comment]
Specify a name in your environment file.
