### ISSUE TITLE
TypeError with conda-env 2.4.2 and Python 3

### ISSUE THREAD

**Issue by koverholt** [conda/conda-env#175]
This works with Python 2, but the below error occurs with Python 3.

Failed command:

```
$ conda env upload
Uploading environment anaconda-cluster-dev to anaconda-server (https://api.anaconda.org)...
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/koverholt/anaconda/bin/conda-env", line 6, in <module>
    sys.exit(main())
  File "/Users/koverholt/anaconda/lib/python3.4/site-packages/conda_env/cli/main.py", line 68, in main
    return args_func(args, parser)
  File "/Users/koverholt/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/Users/koverholt/anaconda/lib/python3.4/site-packages/conda_env/cli/main_upload.py", line 101, in execute
    info = uploader.upload()
  File "/Users/koverholt/anaconda/lib/python3.4/site-packages/conda_env/utils/uploader.py", line 84, in upload
    distribution_type=ENVIRONMENT_TYPE, attrs=self.env_data)
  File "/Users/koverholt/anaconda/lib/python3.4/site-packages/binstar_client/__init__.py", line 409, in upload
    _hexmd5, b64md5, size = compute_hash(fd, size=size)
  File "/Users/koverholt/anaconda/lib/python3.4/site-packages/binstar_client/utils/__init__.py", line 256, in compute_hash
    hash_obj.update(s)
TypeError: Unicode-objects must be encoded before hashing
```

Version:

```
$ conda list conda-env
# packages in environment at /Users/koverholt/anaconda:
#
conda-env                 2.4.2                    py34_0
```

Env file I was attempting to upload:

```
$ cat environment.yml
name: anaconda-cluster-dev
channels:
  - anaconda-cluster
dependencies:
  - python=2.7
  - apache-libcloud=0.18.0
  - pyyaml
  - fabric
  - requests
  - click
  - cython
  - pytest
  - mock
  - pip:
    - pytest-capturelog
```

**Comment by malev** [comment]
@koverholt my first guess is that you are using python 3 and but in your environment.yml file you have python 2 listed as a dependency. I'm gonna take a look anyway

**Comment by koverholt** [comment]
This happens whether I specify `python=2` or `python=3`. Why would the version of Python specified in the `environment.yml` file affect the `conda env upload` command?

**Comment by malev** [comment]
you are right, I don't know why I read `update`. Taking a look
