### ISSUE TITLE
conda env broken

### ISSUE THREAD

**Issue by ijstokes** [conda/conda-env#177]
I am not sure who to ask about conda env. Until we have a replacement, it seems like this is something we need to keep supporting and keep working. Right now it does not appear to work. The following sequence, which is one of the primary use cases (if not the primary use case) seems to be broken due to invalid characters in the auto-gen version:

```bash
mary$ conda env upload                   # uploads environment.yml file from current directory
jess$ conda env create ijstokes/pingpong # downloads and creates environment
```

results in:

```bash
Traceback (most recent call last):
  File "/Users/ijstokes/anaconda/bin/conda-env", line 6, in <module>
    sys.exit(main())
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda_env/cli/main.py", line 68, in main
    return args_func(args, parser)
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda_env/cli/main_create.py", line 78, in execute
    env = spec.environment
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda_env/specs/binstar.py", line 86, in environment
    'original': d['version']} for d in self.file_data]
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 26, in normalized_version
    return VersionOrder(version)
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 151, in __init__
    raise ValueError(message + "invalid character(s).")
ValueError: Malformed version string '2015.10.05-1232': invalid character(s).
```

**Comment by malev** [comment]
@ijstokes working here. Am I doing something wrong?
```
 tmp  conda env create ijstokes/pingpong
Fetching package metadata: ............
Solving package specifications: .Fetching packages ...
apache-libclou 100% |###########################################################################################################| Time: 0:00:19  70.99 kB/s
click-4.1-py27 100% |###########################################################################################################| Time: 0:00:00 133.19 kB/s
cython-0.23.4- 100% |###########################################################################################################| Time: 0:01:23  27.53 kB/s
ecdsa-0.11-py2 100% |###########################################################################################################| Time: 0:00:00 100.01 kB/s
py-1.4.30-py27 100% |###########################################################################################################| Time: 0:00:04  30.10 kB/s
paramiko-1.15. 100% |###########################################################################################################| Time: 0:00:04  46.21 kB/s
fabric-1.10.2- 100% |###########################################################################################################| Time: 0:00:01  99.02 kB/s
pytest-2.8.1-p 100% |###########################################################################################################| Time: 0:00:06  37.23 kB/s
setuptools-18. 100% |###########################################################################################################| Time: 0:00:06  57.46 kB/s
Extracting packages ...
[      COMPLETE      ]|##############################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|##############################################################################################################################| 100%
Collecting pytest-capturelog
  Downloading pytest-capturelog-0.7.tar.gz
Requirement already satisfied (use --upgrade to upgrade): py>=1.1.1 in /Users/mvanetta/miniconda3/envs/anaconda-cluster-dev/lib/python2.7/site-packages (from pytest-capturelog)
Building wheels for collected packages: pytest-capturelog
  Running setup.py bdist_wheel for pytest-capturelog
  Stored in directory: /Users/mvanetta/Library/Caches/pip/wheels/0e/ec/60/ca8f686f34d7c3a89e44003e381be02a693c1a050e51fdf5fe
Successfully built pytest-capturelog
Installing collected packages: pytest-capturelog
Successfully installed pytest-capturelog-0.7
#
# To activate this environment, use:
# $ source activate anaconda-cluster-dev
#
# To deactivate this environment, use:
# $ source deactivate
#
☁  tmp
```

**Comment by ijstokes** [comment]
This is an Anaconda Server issue, AFAICT.  https://github.com/Anaconda-Server/anaconda-server/issues/849

**Comment by ijstokes** [comment]
@malev This is weird: I don't understand how it worked for you, but not for me.  Can you try `conda env create ijstokes/usgs`?

If that works, please can you let me know what version of `conda`, `anaconda-client` and `conda-env` you are using?

TIA!

**Comment by ijstokes** [comment]
@srossross has just confirmed that versions are created on the client side, so back to this being a `conda-env` issue, not Anaconda Server.
