### ISSUE TITLE
Removal of args_func in conda breaks conda-env

### ISSUE THREAD

**Issue by groutr** [conda/conda-env#265]
```
>conda env list
Traceback (most recent call last):
  File "C:\Users\Miniconda3\Scripts\conda-env-script.py", line 3, in <module>
    import conda_env.cli.main
  File "C:\Users\Miniconda3\lib\site-packages\conda_env\cli\main.py", line 28, in <module>
    raise e
  File "C:\Users\Miniconda3\lib\site-packages\conda_env\cli\main.py", line 6, in <module>
    from conda.cli.main import args_func
ImportError: cannot import name 'args_func'
Subprocess exiting:  1
```
`args_func` seems to have disappeared from conda/cli/main.py within the last month.

**Comment by groutr** [comment]
cc @kalefranz
