### ISSUE TITLE
`conda env upload` fails when using conda-canary::conda-env=4.2

### ISSUE THREAD

**Issue by ijstokes** [conda/conda-env#268]
I think this trace shows the problem.  Downgrading to 4.1 (also shown) allowed `conda env upload` to succeed.

```
(test) ➜  2016_08_PyDataSF conda env upload
Using Anaconda Cloud api site https://api.anaconda.org
Uploading environment pydatasf to anaconda-server (https://api.anaconda.org)... 
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.2.3
       conda is private : False
      conda-env version : 2.6.0
    conda-build version : 1.21.2
         python version : 2.7.12.final.0
       requests version : 2.10.0
       root environment : /Users/ijstokes/anaconda  (writable)
    default environment : /Users/ijstokes/anaconda/envs/test
       envs directories : /Users/ijstokes/anaconda/envs
          package cache : /Users/ijstokes/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/t/<TOKEN>/anaconda-mosaic
                          defaults
            config file : /Users/ijstokes/.condarc
           offline mode : False



`$ /Users/ijstokes/anaconda/bin/conda-env upload`




    Traceback (most recent call last):
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 442, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda_env/cli/main_upload.py", line 101, in execute
        info = uploader.upload()
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda_env/utils/uploader.py", line 85, in upload
        distribution_type=ENVIRONMENT_TYPE, attrs=self.env_data)
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 474, in upload
        self._check_response(res)
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 196, in _check_response
        raise ErrCls(msg, res.status_code)
    NotFound: (u"release version=u'2016.08.14.0851' does not exist", 404)

(test) ➜  2016_08_PyDataSF conda install conda=4.1
Fetching package metadata .........
InstallError: Install error: Error: 'conda' can only be installed into the root environment


(test) ➜  2016_08_PyDataSF source activate root
(root) ➜  2016_08_PyDataSF conda install conda=4.1
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /Users/ijstokes/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.5.2            |           py27_0          26 KB
    conda-4.1.11               |           py27_0         201 KB
    ------------------------------------------------------------
                                           Total:         227 KB

The following packages will be SUPERCEDED by a higher-priority channel:

    conda:     4.2.3-py27_0 conda-canary --> 4.1.11-py27_0
    conda-env: 2.6.0-0      conda-canary --> 2.5.2-py27_0 

Proceed ([y]/n)? y

Fetching packages ...
conda-env-2.5. 100% |#######################################################################################################################| Time: 0:00:00 343.40 kB/s
conda-4.1.11-p 100% |#######################################################################################################################| Time: 0:00:00 650.16 kB/s
Extracting packages ...
[      COMPLETE      ]|##########################################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##########################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|##########################################################################################################################################| 100%
(root) ➜  2016_08_PyDataSF conda env upload       
Using Anaconda Cloud api site https://api.anaconda.org
Uploading environment pydatasf to anaconda-server (https://api.anaconda.org)... 
Your environment file has been uploaded to https://anaconda.org/ijstokes/pydatasf
Done.
```

**Comment by HugoTian** [comment]
Could you give me the environment.yml ?

I cannot reproduce the error, and the trace back info is confusing

Thanks
