### ISSUE TITLE
Request  - Versioning of Conda Envs

### ISSUE THREAD

**Issue by jerowe** [conda/conda-env#270]
Hello,

I would like to be able to version environments the way I do packages.

When I use anaconda to upload a conda env it creates a version number from the current datetime. Instead I would like something 1.0, 1.1, etc.

With uploading the relevant code is in 'conda_env.utils.uploader', and there is a function version. Currently this returns the relevant datetime. Instead I would like it to look at a specified version in the environment.yml file, and if that's not found go about creating its usual version.

I can, btw, create an environment.yml file with a version field, and upload that to conda env. The version field doesn't actually do anything, but its there and doesn't get any errors. When I try to install that with conda env create user/package/2016.08.23.1114, I get the following stack trace.

`
Traceback (most recent call last):
  File "/home/jillian/.local/easybuild/software/anaconda/3-4.0.0/bin/conda-env", line 6, in <module>
    sys.exit(conda_env.cli.main.main())
  File "/home/jillian/.local/easybuild/software/anaconda/3-4.0.0/lib/python3.5/site-packages/conda_env/cli/main.py", line 68, in main
    return args_func(args, parser)
  File "/home/jillian/.local/easybuild/software/anaconda/3-4.0.0/lib/python3.5/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/home/jillian/.local/easybuild/software/anaconda/3-4.0.0/lib/python3.5/site-packages/conda_env/cli/main_create.py", line 77, in execute
    env = spec.environment
  File "/home/jillian/.local/easybuild/software/anaconda/3-4.0.0/lib/python3.5/site-packages/conda_env/specs/binstar.py", line 93, in environment
    return env.from_yaml(self._environment)
  File "/home/jillian/.local/easybuild/software/anaconda/3-4.0.0/lib/python3.5/site-packages/conda_env/env.py", line 65, in from_yaml
    return Environment(**data)
TypeError: __init__() got an unexpected keyword argument 'version'
`

I've poked around enough in the code that I could probably implement this, but I'm not sure if anyone else would like to have it.

**Comment by jerowe** [comment]
I can, btw, do this.

```
> anaconda show jerowe/gencore_build_1.0/2016.08.24.1415       
Using Anaconda API: https://api.anaconda.org
version 2016.08.24.1415
   + environment-1.0.yml
None
```

So searching based on version is supported by anaconda.

**Comment by jerowe** [comment]
Aaah, so I think the relevant code is in conda_env.env, the class Environment needs a version attribute added. The version in the uploader will have to be changed to match this.
