### ISSUE TITLE
conda env with no arguments

### ISSUE THREAD

**Issue by asmeurer** [conda/conda-env#56]
```
$conda env
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda/bin/conda-env", line 6, in <module>
    sys.exit(main())
  File "/Users/aaronmeurer/anaconda/lib/python3.4/site-packages/conda_env/cli/main.py", line 53, in main
    return args_func(args, parser)
  File "/Users/aaronmeurer/Documents/Continuum/conda/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
AttributeError: 'Namespace' object has no attribute 'func'
```

**Comment by tswicegood** [comment]
That's weird.  I added in code to make that default to `--help`.  Let me see what happened.

**Comment by asmeurer** [comment]
I've seen this kind of error before, so maybe there needs to be some checking in `args_func`.

**Comment by tswicegood** [comment]
So I did fix it, just not on a branch that ever got released: see https://github.com/conda/conda-env/pull/17/files#r20045117.

That's not the exact fix for `conda-env` right now, but I've got something in the works.  Will have 2.1.2 out in a little bit.
