### ISSUE TITLE
conda env export / conda env create roundtrip doesn't work for dev packages

### ISSUE THREAD

**Issue by tswicegood** [conda/conda-env#71]
_From @cjw296 on April 12, 2015 14:0_

To reproduce:

```
conda env export > environment.yml
cd ~/anaconda/envs
rm -rf picky
cd -
$ conda env create 
Fetching package metadata: ....
Solving package specifications: Linking packages ...
[      COMPLETE      ]|###########################################################################################| 100%
You are using pip version 6.0.8, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Exception:
Traceback (most recent call last):
  File "/Users/chris/anaconda/envs/pickyconda/lib/python2.7/site-packages/pip/basecommand.py", line 232, in main
    status = self.run(options, args)
  File "/Users/chris/anaconda/envs/pickyconda/lib/python2.7/site-packages/pip/commands/install.py", line 305, in run
    name, None, isolated=options.isolated_mode,
  File "/Users/chris/anaconda/envs/pickyconda/lib/python2.7/site-packages/pip/req/req_install.py", line 181, in from_line
    isolated=isolated)
  File "/Users/chris/anaconda/envs/pickyconda/lib/python2.7/site-packages/pip/req/req_install.py", line 54, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/Users/chris/anaconda/envs/pickyconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2873, in parse
    reqs = list(parse_requirements(s))
  File "/Users/chris/anaconda/envs/pickyconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2820, in parse_requirements
    "version spec")
  File "/Users/chris/anaconda/envs/pickyconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2785, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ('Expected version spec in', 'picky (/Users/chris/LocalGIT/picky)==0.0.dev0', 'at', ' (/Users/chris/LocalGIT/picky)==0.0.dev0')
```

The problematic line is in the pip section created by "conda env export":

```
  - picky (/Users/chris/LocalGIT/picky)==0.0.dev0
```

_Copied from original issue: conda/conda#1270_

**Comment by tswicegood** [comment]
_From @cjw296 on April 13, 2015 20:47_

@tswicegood - this is one that will prevent me using environment.yml, my most common used case would be:

```
git clone ...
cd ...
conda env create
```

...but my environment.yml *would* contain at least one package (the one in the checkout ;-)) that would need to be installed with `pip install -e .`

**Comment by tswicegood** [comment]
Sorry for the spam @cjw296 -- just wanted to get this in rigth place.

---

This is a problem I had't thought of.  `environment.yml` is generally meant for working with packages that have been distributed.  Do you have to do `pip install -e .` on the current code, or is a simple `python setup.py develop` enough to make it work for you?  I can see how this would be useful for packages that are distributed via conda, but might want to install themselves locally when in development mode.

If the main issue is being able to have `import picky` work, would something like this in the YAML file work?

```yaml
name: my-env
options:
  - develop: true
```

**Comment by cjw296** [comment]
What's the difference between `pip install -e .` and `python setup.py develop`?

I do, on occasion, need to do `pip install -e .[feature1,feature2,]` which is the pathalogical case.

your 'options' suggestion is interesting but feels like extra knowledge would be needed. Having the pip section basically be a requirements.txt would be the way I would expect it to work.

I'm also totally okay with having environment.yml and requirements.txt, which is actually better as it means existing tools that support requirements.txt (hi pycharm!) will keep working.

If we split them back into two files, then environment.yml could have something like:

```
pip
 - requirements: requirement.txt
```

...to say "please can you also install my pip requirements from this file" rather than having to duplicate the purpose of requirements.txt inside environment.yml.

**Comment by tswicegood** [comment]
> What's the difference between pip install -e . and python setup.py develop?

As far as I'm aware, I believe they are identical.  @ilanschnell, @asmeurer, @srossross: do you guys know of any other differences?

----

In thinking about this, I do like the idea of supporting requirements files.  If we go that route we push all of that complexity off to pip but if we add the develop mode then we own that.

**Comment by ryanpdwyer** [comment]
I would also find this feature really useful!

**Comment by dan-blanchard** [comment]
The ability to specify a pip `requirements.txt` file within `environment.yml` would be pretty handy.  I have a PR open to add support for working with requirements file directly though, #172.
