### ISSUE TITLE
FileNotFoundError when running `conda help`

### ISSUE THREAD

**Issue by gmarkall** [conda/conda-env#75]
Just installed conda env (first with `conda install conda-env`, then with `conda install -c conda conda-env`, but that didn't result in a different version getting installed anyway).

Now running `conda help` results in a traceback part-way through the output:

```
$ conda help
usage: conda [-h] [-V] [--debug] command ...

conda is a tool for managing and deploying applications, environments and
packages.

positional arguments:
  command
    info         Display information about current conda install.
    help         Displays a list of available conda commands and their help
                 strings.
    list         List linked packages in a conda environment.
    search       Search for packages and display their information. The input
                 is a regular expression. To perform a search with a search
                 string that starts with a -, separate the search from the
                 options with --, like 'conda search -- -h'. A * in the
                 results means that package is installed in the current
                 environment. A . means that package is not installed but is
                 cached in the pkgs directory.
    create       Create a new conda environment from a list of specified
                 packages.
    install      Install a list of packages into a specified conda
                 environment.
    update       Update conda packages to the current version.
    remove       Remove a list of packages from a specified conda environment.
    uninstall    Alias for conda remove. See conda remove --help.
    run          Launches an application installed with Conda.
    config       Modify configuration values in .condarc. This is modeled
                 after the git config command. Writes to the user .condarc
                 file (/home/gmarkall/.condarc) by default.
    init         Initialize conda into a regular environment (when conda was
                 installed as a Python package, e.g. using pip). (DEPRECATED)
    clean        Remove unused packages and caches.
    package      Low-level conda package utility. (EXPERIMENTAL)
    bundle       Create or extract a "bundle package" (EXPERIMENTAL)

optional arguments:
  -h, --help     show this help message and exit
  -V, --version  Show the conda version number and exit.
  --debug        Show debug output.

external commands:
    build        tool for building conda packages
    convert      various tools to convert conda packages
Traceback (most recent call last):
  File "/opt/conda/python3/lib/python3.4/site-packages/conda/utils.py", line 141, in __call__
    res = cache[key]
KeyError: (<function Completer.get_items at 0x7f2e3cc0d730>, (), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/python3/bin/conda-develop", line 5, in <module>
    sys.exit(main())
  File "/opt/conda/python3/lib/python3.4/site-packages/conda_build/main_develop.py", line 36, in main
    args = p.parse_args()
  File "/opt/conda/python3/lib/python3.4/argparse.py", line 1728, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/opt/conda/python3/lib/python3.4/argparse.py", line 1760, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/conda/python3/lib/python3.4/argparse.py", line 1966, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/opt/conda/python3/lib/python3.4/argparse.py", line 1906, in consume_optional
    take_action(action, args, option_string)
  File "/opt/conda/python3/lib/python3.4/argparse.py", line 1834, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/conda/python3/lib/python3.4/argparse.py", line 1016, in __call__
    parser.print_help()
  File "/opt/conda/python3/lib/python3.4/argparse.py", line 2359, in print_help
    self._print_message(self.format_help(), file)
  File "/opt/conda/python3/lib/python3.4/argparse.py", line 2343, in format_help
    return formatter.format_help()
  File "/opt/conda/python3/lib/python3.4/argparse.py", line 278, in format_help
    help = self._root_section.format_help()
  File "/opt/conda/python3/lib/python3.4/argparse.py", line 208, in format_help
    func(*args)
  File "/opt/conda/python3/lib/python3.4/argparse.py", line 208, in format_help
    func(*args)
  File "/opt/conda/python3/lib/python3.4/argparse.py", line 515, in _format_action
    help_text = self._expand_help(action)
  File "/opt/conda/python3/lib/python3.4/argparse.py", line 600, in _expand_help
    choices_str = ', '.join([str(c) for c in params['choices']])
  File "/opt/conda/python3/lib/python3.4/site-packages/conda/cli/common.py", line 49, in __iter__
    return iter(self.get_items())
  File "/opt/conda/python3/lib/python3.4/site-packages/conda/utils.py", line 143, in __call__
    res = cache[key] = self.func(*args, **kw)
  File "/opt/conda/python3/lib/python3.4/site-packages/conda/cli/common.py", line 41, in get_items
    return self._get_items()
  File "/opt/conda/python3/lib/python3.4/site-packages/conda/cli/common.py", line 55, in _get_items
    res.extend(os.listdir(dir))
FileNotFoundError: [Errno 2] No such file or directory: '/home/gmarkall/envs'
failed: /opt/conda/python3/bin/conda-develop --help
    env          positional arguments:
                   {create,export,list,remove,update}
                     create              Create an environment based on an environment file
                     export              Export a given environment
                     list                List the Conda environments
                     remove              Remove an environment
                     update              Update the current environment based on environment
                                         file
    index        Update package index metadata files in given directories
    metapackage  tool for building conda metapackages. A metapackage is a package with no
                 files, only metadata
    pipbuild     tool for building conda packages just using pip install
    skeleton     create skeleton recipes for packages from hosting sites
```

`conda help` worked just before I installed conda-env. Output of `conda info` (in case it's relevant):

```
$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.11.0
  conda-build version : 1.9.0
       python version : 3.4.3.final.0
     requests version : 2.6.2
     root environment : /opt/conda/python3  (read only)
  default environment : /opt/conda/python3
     envs directories : /home/gmarkall/.conda/envs
                        /home/gmarkall/envs
                        /opt/conda/python3/envs
        package cache : /home/gmarkall/.conda/envs/.pkgs
                        /home/gmarkall/envs/.pkgs
                        /opt/conda/python3/pkgs
         channel URLs : http://conda.binstar.org/numba/linux-64/
                        http://conda.binstar.org/numba/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/gmarkall/.condarc
    is foreign system : False
```

**Comment by malev** [comment]
This is working now
