### ISSUE TITLE
No module named "binstar_client"

### ISSUE THREAD

**Issue by campos-ddc** [conda/conda-env#87]
I recently tried to build the development version of `conda_env` and ran into this missing module when trying to run `conda env create`.

It seems to be related to the recent addition of 'upload' commands.

Will `binstar` be a mandatory dependency of `conda_env`? If so, shouldn't it be declared in `conda.recipe/meta.yml`?

**Comment by malev** [comment]
`binstar` should not be a dependency but the error is happening:
```
root@temp:~/tmp# conda env create
Traceback (most recent call last):
  File "/root/miniconda/bin/conda-env", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/root/conda-env/bin/conda-env", line 3, in <module>
    from conda_env.cli.main import main
  File "/root/conda-env/conda_env/cli/main.py", line 35, in <module>
    from . import main_upload
  File "/root/conda-env/conda_env/cli/main_upload.py", line 6, in <module>
    from ..utils.uploader import is_installed, Uploader
  File "/root/conda-env/conda_env/utils/uploader.py", line 8, in <module>
    from binstar_client import errors
```
